Allow different locations for syslinux dir.  Convert isolinux if needed

diff --git a/live-usb-maker b/live-usb-maker
--- a/live-usb-maker
+++ b/live-usb-maker
@@ -530,9 +530,31 @@ do_install() {
     done
 
     [ "$file" ] || fatal 230 "Could not find file $fname"
-    cmd dd bs=440 conv=notrunc count=1 if=$file of=$usb_dev || fatal "dd command failed"
+    cmd dd bs=440 conv=notrunc count=1 if=$file of=$usb_dev > /dev/null || fatal "dd command failed"
 
-    cmd extlinux -i $ext_dir/boot/syslinux || fatal 231 "extlinux command failed"
+    local sdir idir syslinux_dir isolinux_dir
+    for sdir in boot/syslinux syslinux; do
+        test -d $ext_dir/$sdir || continue
+        syslinux_dir=$ext_dir/$sdir
+        break
+    done
+    if [ -z "$syslinux_dir" ]; then
+        for idir in boot/isolinux isolinux; do
+            test -d $ext_dir/$idir || continue
+
+            warn "Create syslinux directory from %s" $idir
+                syslinux_dir=$ext_dir/${idir%isolinux}syslinux
+                cmd cp -r $ext_dir/$idir $syslinux_dir || fatal 231 "Could not copy the isolinux directory"
+                local f
+                for f in $(cd $syslinux_dir && ls isolinux.*); do
+                    test -e $ext_dir/$sdir/$f || continue
+                    cmd mv $ext_dir/$sdir/$f $ext_dir/$sdir/syslinux${f#isolinux}
+                done
+            break
+        done
+    fi
+    [ "$syslinux_dir" ] || fatal 232 "Could not find a syslinux or isolinux directory"
+    cmd extlinux -i $syslinux_dir || fatal 233 "extlinux command failed"
 }
 
 need() {
