Fix bug "in missing cryptsetup" error message.
Keep unpack-initrd output out of log file due to ansi escape colors

diff --git a/live-usb-maker b/live-usb-maker
--- a/live-usb-maker
+++ b/live-usb-maker
@@ -1560,7 +1560,7 @@ enable_initrd_encryption() {
     local from_file=${1:-$2}  to_file=$2  dir=${3:-$INITRD_DIR}  mod_dir=$4
 
     test -r "$from_file" || fatal "Could not find initrd file %s" "$(pqw $from_file)"
-    always_cmd unpack-initrd -f "$from_file" -d $dir || fatal "An error occurred unpacking the initrd"
+    unpack-initrd -f "$from_file" -d $dir || fatal "An error occurred unpacking the initrd"
 
     pause initrd
 
@@ -1594,12 +1594,12 @@ enable_disable_initrd_encryption() {
     local from_file=${1:-$2}  to_file=$2  dir=${3:-$INITRD_DIR}
 
     test -r "$from_file" || fatal "Could not find initrd file %s" "$(pqw $from_file)"
-    always_cmd unpack-initrd -f "$from_file" -d $dir || fatal "An error occurred unpacking the initrd"
+    unpack-initrd -f "$from_file" -d $dir || fatal "An error occurred unpacking the initrd"
 
 
     local encrypt_file=$dir/etc/encrypt
     if encrypt; then
-        test -e $dir/bin/cryptsetup  || fatal "The % program not found in the initrd" cryptsetup
+        test -e $dir/bin/cryptsetup  || fatal "The %s program not found in the initrd" cryptsetup
         grep -q cryptsetup $dir/init || fatal "This initrd cannot do encryption"
 
         msg $"Enable encryption in the live initrd"
