Add a check_target() routine to better mesh cmdline with menus

diff --git a/live-usb-maker b/live-usb-maker
--- a/live-usb-maker
+++ b/live-usb-maker
@@ -801,6 +801,19 @@ do_install_bootloader() {
     cmd extlinux -i $syslinux_dir || fatal "%s command failed" extlinux
 }
 
+check_target() {
+    local target=$1  live_dev=$2
+
+    # Make sure our target is a real device
+    local target_dev=$(expand_device $target)
+
+    [ ${#target_dev} -gt 0 ] || fatal $"Could not find device %s" "$target"
+    [ ${#live_dev}   -gt 0 ] || return
+    local live_drive=$(get_drive ${live_dev##*/} )
+    local targ_drive=$(get_drive ${target##*/}   )
+    [ "$live_drive" = "$targ_drive" ] && fatal "Target '%s' cannot be on the live device '%s'" "$target" "$live_drive"
+}
+
 #------------------------------------------------------------------------------
 #
 #------------------------------------------------------------------------------
