Beef up finding the lib

diff --git a/live-usb-maker b/live-usb-maker
--- a/live-usb-maker
+++ b/live-usb-maker
@@ -651,6 +651,7 @@ start_log() {
 $ME
     started: $(date)
 comand line: $args
+  found lib: $FOUND_LIB
    commands: $cmds
    iso file: $iso
      device: $dev
@@ -675,26 +676,29 @@ clean_up() {
 }
 
 load_lib() {
-    local file=$1
+    local file=$1 path=$2
     shift
 
-    local dir lib found
-    for dir; do
+    unset FOUND_LIB
+    local dir lib found orig_ifs=$IFS
+    IFS=:
+    for dir in $path; do
         lib=$dir/$file
-        test -e $lib || continue
-        test -r $lib || return 1
+        test -r $lib || continue
         . $lib || return 2
-        found=1
+        FOUND_LIB=$lib
         break
     done
-    [ "$found" ]
-    return $?
+    IFS=$orig_ifs
+    [ "$FOUND_LIB" ] && return 0
+    return 3
 }
 
 #===== Start Here =============================================================
-if ! load_lib "$SHELL_LIB" "$LIB_PATH" "$MY_DIR/../cli-shell-utils" "$MY_DIR"; then
-    echo "Could not find library '%s' on path '%s'" "$SHELL_LIB" "$LIB_PATH" >&2
-    echo "This is a fatal error" >&2
+LIB_PATH="$LIB_PATH:$MY_DIR/../cli-shell-utils:$MY_DIR"
+if ! load_lib "$SHELL_LIB" "$LIB_PATH" ; then
+    printf "Could not find library '%s' on path '%s'\n" "$SHELL_LIB" "$LIB_PATH" >&2
+    printf "This is a fatal error\n" >&2
     exit 17
 fi
 
