Fix bug in "gui" mode so we don't ask about live-boot directory

diff --git a/live-usb-maker b/live-usb-maker
--- a/live-usb-maker
+++ b/live-usb-maker
@@ -718,8 +718,15 @@ clone_directory() {
     # FIXME: should this error message have a device, not a directory?
     local boot_dir
     # No <file-name> file found in any directory on clone device at <root-directory>
-    find_live_boot_dir boot_dir "$from_dir" "$LINUXFS_NAME" \
-        || fatal $"No '%s' file found in any directory on clone device at '%s'" "$LINUXFS_NAME" "$from_dir"
+    find_live_boot_dir boot_dir "$from_dir" "$LINUXFS_NAME"
+    local ret=$?
+    case $ret in
+        0) ;;
+        1) fatal $"No '%s' file found in any directory on clone device at '%s'" "$LINUXFS_NAME" "$from_dir" ;;
+        2) fatal $"No live-boot directory found on clone device at '%s'"          "$from_dir" ;;
+        3) fatal $"Multiple live-boot directories found on clone device at '%s'"  "$from_dir" ;;
+        *) fatal "Internal error in find_live_boot_dir()"
+    esac
 
     msg "Live boot directory %s" "$(pq $boot_dir)"
 
