Allow external progress bar program
Designed to work with "yad --progress"

diff --git a/live-usb-maker b/live-usb-maker
--- a/live-usb-maker
+++ b/live-usb-maker
@@ -144,7 +144,8 @@ Options:
                             makefs: Make the ext4 filesystem even if one exists
                               copy: Overwrite ext4 partition even if antiX/ exists
                                all: All of the above (dangerous!)
-
+  -- --gui-progress     All remaining args are used as a gui progress bar program
+                        Example: --gui-progress yad --progress --auto-close
   -g --gpt              Use gpt partitioning (default) instead of msdos
   -h --help             Show this usage
   -i --initrd=<file>    Start with <file> for making encrypt enabled initrd
@@ -210,6 +211,7 @@ eval_argument() {
               -from|f)  FROM=$val                        ;;
               -from=*)  FROM=$val                        ;;
                -gpt|g)  MSDOS_GPT="gpt"                  ;;
+      -gui-progress|-)  END_CMDLINE=true                 ;;
             -initrd|i)  INITRD_FILE=$val                 ;;
      -keep-syslinux|k)  KEEP_SYSLINUX=true               ;;
              -label|L)  BIOS_LABEL=$val                  ;;
@@ -267,7 +269,7 @@ takes_param() {
 }
 
 main() {
-    local SHIFT SHORT_STACK="bcCDeEfFghIkLmnpPqRstvVW"
+    local SHIFT SHIFT_2 SHORT_STACK="bcCDeEfFghIkLmnpPqRstvVW"
     local BE_VERBOSE FROM TARGET FATAL_QUESTION CMD PARAM_CNT ENCRYPT
     local START_T=0
     set_colors
@@ -325,6 +327,12 @@ main() {
 
     shout $"Starting %s" "$ME"
     start_log "$orig_args" "$CMDS"
+
+    shift $SHIFT_2
+    if [ $# -gt 0 ]; then
+        echo "Will use progress program: $*" >> $LOG_FILE
+        which "$1" &>/dev/null || fatal "Could not find progress program %s" "$(pqh $1)"
+    fi
 
     shout_pretend
 
@@ -589,7 +597,7 @@ main() {
 
     need copy-uefi && copy_files_spec $ISO_DIR "$UEFI_FILES" "$UEFI_DIR" uefi
 
-    need copy-main && do_copy_main $ISO_DIR $MAIN_DIR
+    need copy-main && do_copy_main $ISO_DIR $MAIN_DIR  "$@"
 
     local bios_uuid=$(lsblk -no uuid $BIOS_DEV)
     local uefi_uuid=$(lsblk -no uuid $UEFI_DEV)
@@ -1121,23 +1129,27 @@ do_makefs_uefi() {
 # Copy from mounted source (or the clone) to the ext4 partition
 #------------------------------------------------------------------------------
 do_copy_main() {
-    local iso_dir=$1  main_dir=$2  files="*"
+    local from=$1  to=$2  ;  shift 2
 
-    if test -d $main_dir/antiX && ! force copy; then
-        pwarn "Not over-writing %s partition due to existing %s directory" ext antiX/
+    if false && test -d $to/antiX && ! force copy; then
+        pwarn "Not over-writing %s partition due to existing %s directory" main antiX/
         pwarn "Use %s to overwrite" "--force=copy"
         return
     fi
 
+    msg $"copy from %s to %s partition" "$(pq $(basename $from))" "$(pq $(basename $to))"
+    msg $"files: %s" "$(pq "*")"
+
     local err_msg=$"Error while copying files to main partition of live usb"
 
-    msg "copy files from %s to %s partition" "$(pq $(basename $iso_dir))" "$(pq $(basename $main_dir))"
-    msg "files: %s" "$(pq "$files")"
+    if [ $# -gt 0 ]; then
+        copy_with_progress "$from/*" "$to" "$err_msg" "$@"
 
-    if q_mode gui || [ "$NO_PROGRESS_BAR" ]; then
-        cmd cp -a $iso_dir/$files $main_dir/ || fatal "$err_msg"
+    elif q_mode gui || [ "$NO_PROGRESS_BAR" ]; then
+        cmd cp -a $from/* $to/ || fatal "$err_msg"
+
     else
-        [ -z "$PRETEND" ] && progbar_copy "$iso_dir" "$main_dir" "$err_msg"
+        copy_with_progress "$from/*" "$to" "$err_msg" text_progress
     fi
 
     sync
@@ -1153,7 +1165,7 @@ copy_files_spec() {
 
     test -z "$spec" && fatal "Missing list of files to copy to %s" "$(pqw $targ)"
 
-    msg "copy files from %s to %s partition" "$(pq $(basename $src))" "$(pq $(basename $targ))"
+    msg "copy from %s to %s partition" "$(pq $(basename $src))" "$(pq $(basename $targ))"
     msg "files: %s" "$(pq $spec)"
 
     while read file; do
