Rename usb_dev --> target_dev for better clarity

diff --git a/live-usb-maker b/live-usb-maker
--- a/live-usb-maker
+++ b/live-usb-maker
@@ -281,37 +281,37 @@ main() {
     [ ${#TARGET} -eq 0 ] && select_target_device TARGET "$live_dev" "$from_dev"
 
     # Make sure our target is a real device
-    local usb_dev=$(expand_device $TARGET)
-    [ ${#usb_dev} -gt 0 ] || fatal $"Could not find device %s" "$TARGET"
+    local target_dev=$(expand_device $TARGET)
+    [ ${#target_dev} -gt 0 ] || fatal $"Could not find device %s" "$TARGET"
 
     # Present cheat menus if no cheats given and --not-cheats not given
     [ ${#CHEATS} -eq 0  -a -z "$NO_CHEATS" ] && cheats_menus CHEATS
 
     #--- Okay, now we are ready for final checks and to do the work
     # We start logging right after we've expanded the target device
-    start_log "$orig_args" "$CMDS" "$FROM" "$usb_dev"
+    start_log "$orig_args" "$CMDS" "$FROM" "$target_dev"
 
     mkdir -p $WORK_DIR || fatal $"Could not make a work directory under /tmp"
     mount -t tmpfs tmpfs $WORK_DIR || fatal $"Could not mount tmpfs at %s" $WORK_DIR
 
     # This are mostly for a manually entered target
-    test -e $usb_dev || fatal $"Target device %s does not exist" $usb_dev
-    test -b $usb_dev || fatal $"Target device %s is not a block device" $usb_dev
+    test -e $target_dev || fatal $"Target device %s does not exist" $target_dev
+    test -b $target_dev || fatal $"Target device %s is not a block device" $target_dev
 
     # Require that an entire disk device be specified (could relax?)
-    local dev_type=$(lsblk -no type --nodeps $usb_dev)
-    [ "$dev_type" = "disk" ] || fatal $"Device %s is not a disk device" $usb_dev
+    local dev_type=$(lsblk -no type --nodeps $target_dev)
+    [ "$dev_type" = "disk" ] || fatal $"Device %s is not a disk device" $target_dev
 
     # Get first to partitions (lexically only)
-    local ext_dev=$(get_partition $usb_dev 1)
-    local fat_dev=$(get_partition $usb_dev 2)
+    local ext_dev=$(get_partition $target_dev 1)
+    local fat_dev=$(get_partition $target_dev 2)
 
     # fatal "The device %s does not seem to be usb or removable."
     # FIXME: move this to the lib
-    force usb || is_usb_or_removable $usb_dev || yes_NO_fatal "usb" \
+    force usb || is_usb_or_removable $target_dev || yes_NO_fatal "usb" \
         $"Do you want to use it anyway (dangerous)?" \
         $"Use %s to always ignore this warning"      \
-        $"The device %s does not seem to be usb or removeable."  "$usb_dev"
+        $"The device %s does not seem to be usb or removeable."  "$target_dev"
 
     # Set up our directories.  These a GLOBALS so they can be used in clean_up() on exit
     ISO_DIR=$WORK_DIR/iso
@@ -334,7 +334,7 @@ main() {
     fi
 
     #--- calculate and show various sizes before we through errors due to size
-    local total_size=$(parted $usb_dev unit MiB print | sed -rn "s/^Disk.*: ([0-9]+)MiB$/\1/p")
+    local total_size=$(parted $target_dev unit MiB print | sed -rn "s/^Disk.*: ([0-9]+)MiB$/\1/p")
     local mib_size=$((total_size * SIZE / 100 - 1))
     local ext_size=$((mib_size - FAT_SIZE))
     local ext_needed=$(du_size $ISO_DIR/*)
@@ -362,12 +362,12 @@ main() {
     given_cmd sizes && my_exit 0
 
     # Make sure the target is not in use
-    umount_all $usb_dev
+    umount_all $target_dev
 
     #--- One last check with the user before we start doing the work
     YES_no_pretend || my_exit
 
-    need partition && do_partition "$usb_dev" "$MBR_GPT" $ext_size $mib_size
+    need partition && do_partition "$target_dev" "$MBR_GPT" $ext_size $mib_size
 
     need makefs-ext && do_makefs_ext "$ext_dev" "$EXT4_OPTIONS" "$EXT4_LABEL"
     need makefs-fat && do_makefs_fat $fat_dev
@@ -392,7 +392,7 @@ main() {
     [ ${#CHEATS} -gt 0 ] && need cheats-syslinux && do_cheats_syslinux $EXT_DIR "$CHEATS"
     [ ${#CHEATS} -gt 0 ] && need cheats-grub     && do_cheats_grub     $FAT_DIR "$CHEATS"
 
-    need install && do_install $usb_dev $EXT_DIR $MBR_GPT
+    need install && do_install $target_dev $EXT_DIR $MBR_GPT
 
     my_exit 0
 }
@@ -583,12 +583,12 @@ do_partition() {
 
     msg $"Using %s partitioning" $(pq $type)
 
-    cmd parted --script --align optimal $usb_dev   \
-        unit MiB                                   \
-        mklabel $type                              \
-        mkpart primary ext4  1         $ext_size   \
-        mkpart primary fat32 $ext_size $mib_size   \
-        set 1 $boot_flag on                        \
+    cmd parted --script --align optimal $target_dev \
+        unit MiB                                    \
+        mklabel $type                               \
+        mkpart primary ext4  1         $ext_size    \
+        mkpart primary fat32 $ext_size $mib_size    \
+        set 1 $boot_flag on                         \
         set 2 esp  on || fatal $"Partitioning failed"
 }
 
@@ -729,7 +729,7 @@ do_uuids() {
 #
 #------------------------------------------------------------------------------
 do_install() {
-    local usb_dev=$1  ext_dir=$2  type=$3
+    local target_dev=$1  ext_dir=$2  type=$3
 
     local fname
     case $type in
@@ -747,7 +747,7 @@ do_install() {
     done
 
     [ "$file" ] || fatal $"Could not find file %s" "$fname"
-    cmd dd bs=440 conv=notrunc count=1 if=$file of=$usb_dev > /dev/null || fatal $"%s command failed" dd
+    cmd dd bs=440 conv=notrunc count=1 if=$file of=$target_dev > /dev/null || fatal $"%s command failed" dd
 
     local sdir idir syslinux_dir isolinux_dir
     for sdir in boot/syslinux syslinux; do
