Check md5 of files copied to the live-usb
Duh!

diff --git a/live-usb-maker b/live-usb-maker
--- a/live-usb-maker
+++ b/live-usb-maker
@@ -101,11 +101,11 @@ BACKUP_WORDS_FILE="/usr/share/dict/words"
 
     EXT4_NO_64BIT="-O ^64bit"
 
-ORDERED_CMDS="partition-clear partition-make makefs-main makefs-bios makefs-uefi copy-main copy-bios copy-uefi"
-ORDERED_CMDS="$ORDERED_CMDS uuids cheats cheats-syslinux cheats-grub install encrypt-main encryption-initrd"
+ORDERED_CMDS="partition-clear partition-make makefs-main makefs-bios makefs-uefi copy-main check-usb-md5 copy-bios"
+ORDERED_CMDS="$ORDERED_CMDS copy-uefi uuids cheats cheats-syslinux cheats-grub install encrypt-main encryption-initrd"
     ALL_CMDS="sizes all partition makefs copy cheats $ORDERED_CMDS"
 
-   ALL_FORCE="automount,flock,makefs,ultra-fit,usb,nofuse,fuse,uuids"
+   ALL_FORCE="automount,flock,makefs,ultra-fit,usb,nofuse,fuse,uuids,nomd5"
    ALL_PAUSE="exit,initrd,copy,uuids"
 
     LIB_PATH="$MY_LIB_DIR:$LIB_DIR"
@@ -183,6 +183,7 @@ Options:
 
   -F --force=<xxx>      Force the options specfied:
                                usb: Ignore usb/removable check
+                             nomd5: Don't check md5 of files copied to live-usb
                          ultra-fit: don't warn about SanDisk utra-fit devices
                             makefs: Make the ext4 filesystem even if one exists
                          automount: don't temporarily disable antiX automounting
@@ -302,7 +303,7 @@ eval_argument() {
               -size=*)  CMD_SIZE=${val%\%}               ;;
             -target|t)  TARGET=$val                      ;;
             -target=*)  TARGET=$val                      ;;
-            -update|u)  CMD_CMDS="$CMD_CMDS${CMD_CMDS:+ }copy-main"
+            -update|u)  CMD_CMDS="$CMD_CMDS${CMD_CMDS:+ }copy-main check-usb-md5"
                         SAVE_BOOT=true
                         KEEP_SYSLINUX=true               ;;
            -verbose|V)  VERBOSITY=$((VERBOSITY + 1))     ;;
@@ -668,7 +669,8 @@ main() {
 
     # fatal "The device %s does not seem to be usb or removable."
     # FIXME: move this to the lib?
-    force usb || is_usb_or_removable $target_dev || yes_NO_fatal "usb" \
+    force usb || is_usb_or_removable $target_dev \
+        || yes_NO_fatal "usb" \
         "Do you want to use it anyway (dangerous)?" \
         "Use %s to always ignore this warning"      \
         "The device %s does not seem to be usb or removeable."  "$target_dev"
@@ -860,6 +862,8 @@ main() {
         write_random_seed $MAIN_DIR/$DEF_BOOT_DIR/$SEED_FNAME
         test -e "$MAIN_DIR/.disk" && cmd rm -rf "$MAIN_DIR/.disk"
     fi
+
+    ! force nomd5 && have_usb_md5 "$MAIN_DIR" && need check-usb-md5 && check_usb_md5 "$MAIN_DIR"
 
     #need defrag && do_defrag "$MAIN_DIR" "$DEFRAG_ALL"
 
@@ -1199,7 +1203,8 @@ select_other_mode() {
                  quit) not_done=true                             ;;
                format) cmd_val=format-usb                        ;;
                 clear) cmd_val="partition-clear"                 ;;
-               update) cmd_val="copy-main" ; SAVE_BOOT=true      ;;
+               update) cmd_val="copy-main check-usb-md5"
+                       SAVE_BOOT=true                            ;;
                 uuids) cmd_val=$ans                              ;;
                cheats) cmd_val=$ans ; : ${CHEATS:=yes}           ;;
               install) cmd_val=$ans                              ;;
@@ -1881,6 +1886,43 @@ do_copy_main() {
 
     sync ; sync
     pause copy
+}
+
+#------------------------------------------------------------------------------
+# See if there are .md5 files under the given directory
+#------------------------------------------------------------------------------
+have_usb_md5() {
+    local dir=$1
+    [ -n "$(find $dir -maxdepth 3 -name "*.md5" -printf ".")" ]
+    return $?
+}
+
+#------------------------------------------------------------------------------
+# Check the integrity of all files listed in .md5 files
+#------------------------------------------------------------------------------
+check_usb_md5() {
+    local top_dir=$1
+    local md5_file  failed
+    while read md5_file; do
+        local fname=$(basename "$md5_file")
+        local name=${fname%.md5}
+        local dir=$(dirname "$md5_file")
+        msg "check md5 for %s" "$(pq "$name")"
+        (cd $dir && cmd md5sum -c "$fname") && continue
+        warn "MD5 CHECK FAILED FOR %s" "$(pqw $name)"
+        failed=true
+    done << MD5_Files
+$(find "$top_dir" -maxdepth 3 -name "*.md5")
+MD5_Files
+
+    [ -z "$failed" ] && return
+
+    echo
+
+    yes_NO_fatal "nomd5"                         \
+        "Do you want to continue anway?"         \
+        "Use %s to always ignore this warning"   \
+        "At least one file failed the md5 check"
 }
 
 #------------------------------------------------------------------------------
