Get --encrypt to work all the way through in --pretend mode!
Of course, you need to be starting out with an encrypted live-usb.

diff --git a/live-usb-maker b/live-usb-maker
--- a/live-usb-maker
+++ b/live-usb-maker
@@ -967,15 +967,16 @@ encrypt_partition() {
 
     msg $"About to encrypt device %s" "$(pq $dev)"
 
-    LUKS_DEV=/dev/mapper/$name
-    [ "$PRETEND_MODE" ] && return
+    if [ -z "$PRETEND_MODE" ]; then
 
-    cat $file | cryptsetup luksFormat --key-file - $dev \
-        || fatal "Failed to create encrypted device"
+        cat $file | cryptsetup luksFormat --key-file - $dev \
+            || fatal "Failed to create encrypted device"
+    fi
 
     cryptsetup open --type luks --key-file $file $dev $name \
         || fatal "Failed to open encrypted device"
 
+    LUKS_DEV=/dev/mapper/$name
     msg $"Encryption successful"
 }
 
@@ -1249,7 +1250,7 @@ enable_initrd_encryption() {
     local from_file=${1:-$2}  to_file=$2  dir=${3:-$INITRD_DIR}  mod_dir=$4
 
     test -r "$from_file" || fatal "Could not find initrd file %s" "$(pqw $from_file)"
-    cmd unpack-initrd -f "$from_file" -d $dir || fatal "An error occurred unpacking the initrd"
+    always_cmd unpack-initrd -f "$from_file" -d $dir || fatal "An error occurred unpacking the initrd"
 
     pause initrd
 
