Get variables out of fatal error strings

diff --git a/live-usb-maker b/live-usb-maker
--- a/live-usb-maker
+++ b/live-usb-maker
@@ -118,7 +118,7 @@ eval_argument() {
               -size|s)  SIZE=${val%\%}                  ;;
           -size=*|s=*)  SIZE=${val%\%}                  ;;
            -verbose|v)  BE_VERBOSE=true                 ;;
-                    *)  fatal "Unknown parameter -$arg" ;;
+                    *)  fatal "Unknown parameter %s" "-$arg" ;;
     esac
 }
 
@@ -169,7 +169,7 @@ main() {
 
     case $SIZE in
         [1-9]|[0-9][0-9]|100) ;;
-        *) fatal 012 "Bad size format \"%s\".  Should be between 1 and 100 inclusive." "$(pqh $SIZE)"
+        *) fatal 012 "Bad size format '%s'.  Should be between 1 and 100 inclusive." "$(pqh $SIZE)"
     esac
 
     [ -z "${FAT_SIZE##[0-9]}" ] && fatal 013 "esp-size must be larger than 9"
@@ -181,7 +181,7 @@ main() {
     # Test for valid commands and process cmd+ commands
     local cmd plus_cnt=0
     for cmd in $CMDS; do
-        echo "$ALL_CMDS" | egrep -q "(^| )$cmd+?( |$)" || fatal 015 "Unknown command: $cmd"
+        echo "$ALL_CMDS" | egrep -q "(^| )$cmd+?( |$)" || fatal 015 "Unknown command: %s" $cmd
         [ -z "${cmd%%*+}" ] || continue
         cmd=${cmd%+}
         CMDS="$CMDS $(echo "$ORDERED_CMDS" | sed -rn "s/.*($cmd )/\1/p")"
@@ -191,7 +191,7 @@ main() {
 
     local force
     for force in ${FORCE//,/ }; do
-        echo ",$ALL_FORCE," | egrep -q ",$force," || fatal 016 "Unknown force option: $force"
+        echo ",$ALL_FORCE," | egrep -q ",$force," || fatal 016 "Unknown force option: %s" "$force"
     done
 
     EXIT_NUM=100
@@ -200,7 +200,7 @@ main() {
     # Write config file if one does not already exist
     test -e "$CONF_FILE" || write_conf "$CONF_FILE"
 
-    local usb_dev=$(expand_device $DEVICE) || fatal 110 "Could not find device $DEVICE"
+    local usb_dev=$(expand_device $DEVICE) || fatal 110 "Could not find device %s" "$DEVICE"
 
     mkdir -p $WORK_DIR || fatal 120 "Could not make temporary work directory under /tmp"
     chmod 755 $WORK_DIR
@@ -209,10 +209,10 @@ main() {
     start_log "$orig_args" "$CMDS" "$ISO_FILE" "$usb_dev"
 
     local dev_type=$(lsblk -no type --nodeps $usb_dev)
-    [ "$dev_type" = "disk" ] || fatal 130 "Device $usb_dev is not a disk device"
+    [ "$dev_type" = "disk" ] || fatal 130 "Device %s is not a disk device" $usb_dev
 
-    test -e $usb_dev || fatal 140 "Device $usb_dev does not exist"
-    test -b $usb_dev || fatal 150 "Device $usb_dev is not a block device"
+    test -e $usb_dev || fatal 140 "Device %s does not exist" $usb_dev
+    test -b $usb_dev || fatal 150 "Device %s is not a block device" $usb_dev
 
     local ext_dev=$(get_partition $usb_dev 1)
     local fat_dev=$(get_partition $usb_dev 2)
@@ -227,9 +227,9 @@ main() {
     FAT_DIR=$WORK_DIR/fat
     MNT_DIR=$WORK_DIR/live-dev
 
-    mkdir $ISO_DIR $EXT_DIR $FAT_DIR || fatal 160 "Could not make $WORK_DIR subdirectories"
+    mkdir $ISO_DIR $EXT_DIR $FAT_DIR || fatal 160 "Could not make %s subdirectories" "$WORK_DIR"
 
-    mount_iso "$ISO_FILE" $ISO_DIR || fatal 170 "Could not mount iso file $ISO_FILE"
+    mount_iso "$ISO_FILE" $ISO_DIR || fatal 170 "Could not mount iso file %s" "$ISO_FILE"
 
     local iso_version version_file=$ISO_DIR/version
     if test -r $version_file && iso_version=$(cat $version_file 2>/dev/null) \
@@ -259,7 +259,7 @@ main() {
     msg
 
     if [ ${#CMDS} -le 0 ]; then
-        echo -e "No command(s) given.  Try \"all\"."
+        echo -e "No command(s) given.  Try 'all'."
         exit 0
     fi
 
@@ -298,7 +298,7 @@ mount_iso() {
     local file=$1  dir=$2
     mkdir -p $dir
 
-    is_mountpoint $dir && fatal 171 "Directory \"$dir\" is already a mountpoint"
+    is_mountpoint $dir && fatal 171 "Directory '%s' is already a mountpoint" $dir
 
     case $file in
         live) mount_live $dir              ; return ;;
@@ -312,8 +312,8 @@ mount_iso() {
         mount -o ro "$file" $dir
         is_mountpoint $dir && return 0
     else
-        test -e "$file" || fatal 172 "Could not find iso file $file"
-        test -r "$file" || fatal 173 "Could not read iso file $file"
+        test -e "$file" || fatal 172 "Could not find iso file %s" "$file"
+        test -r "$file" || fatal 173 "Could not read iso file %s" "$file"
 
         local type
         for type in iso9660 udf; do
@@ -322,25 +322,25 @@ mount_iso() {
         done
     fi
 
-    fatal 175 "Could not mount iso file $file"
+    fatal 175 "Could not mount iso file %s" "$file"
 }
 
 mount_live() {
     local targ_dir=$1  live_dir=${2:-$LIVE_MP}
 
-    is_mountpoint "$targ_dir" && fatal 181 "Live directory \"$targ_dir\" is already a mountpoint"
+    is_mountpoint "$targ_dir" && fatal 181 "Live directory '%s' is already a mountpoint" "$targ_dir"
 
     # Allow live "directory" to be a device that we mount
     local block_dev=$(expand_device $live_dir)
     if [ ${#block_dev} -gt 0 ];  then
         my_mkdir $MNT_DIR
         mount -o ro $block_dev $MNT_DIR
-        is_mountpoint $MNT_DIR || fatal 182 "Could not mount device $block_dev"
+        is_mountpoint $MNT_DIR || fatal 182 "Could not mount device %s" "$block_dev"
         live_dir=$MNT_DIR
     fi
 
-    test -d "$live_dir"       || fatal 183 "Live directory \"$live_dir\" is not a directory"
-    is_mountpoint "$live_dir" || fatal 184 "Live directory \"$live_dir\" is not a mountpoint"
+    test -d "$live_dir"       || fatal 183 "Live directory '%s' is not a directory"   "$live_dir"
+    is_mountpoint "$live_dir" || fatal 184 "Live directory '%s' is not a mountpoint"  "$live_dir"
 
     mount --bind $targ_dir $targ_dir
 
@@ -352,7 +352,7 @@ mount_live() {
         from="$live_dir/$dir"
         dest="$targ_dir/$dir"
         test -d "$from" || continue
-        mkdir -p "$dest" || fatal 186 "Could not create directory $dest"
+        mkdir -p "$dest" || fatal 186 "Could not create directory %s" "$dest"
         mount --bind "$from" "$dest"
     done <<Live_Dirs
 $(cd "$live_dir" && eval "ls -d $LIVE_DIRS" 2>/dev/null)
@@ -363,8 +363,8 @@ Live_Dirs
         from="$live_dir/$file"
         dest="$targ_dir/$file"
         test -f "$from" || continue
-        mkdir -p "$(dirname "$dest")" || fatal 187 "Could not mkdir $(dirname "$dest")"
-        touch "$dest"                 || fatal 188 "Could not touch file $dest"
+        mkdir -p "$(dirname "$dest")" || fatal 187 "Could not mkdir %s" "$(dirname "$dest")"
+        touch "$dest"                 || fatal 188 "Could not touch file %s" "$dest"
         mount --bind "$from" "$dest"
     done <<Live_Files
 $(cd "$live_dir" && eval "ls -d $LIVE_FILES" 2>/dev/null)
@@ -373,10 +373,10 @@ Live_Files
 
 my_mount() {
     local dev=$1  dir=$2
-    is_mountpoint $dir           && fatal 190 "Directory \"$dir\" is already a mountpoint"
-    PRETEND= cmd mkdir -p $dir   || fatal 191 "Failed to create directory \"$dir\""
-    PRETEND= cmd mount $dev $dir || fatal 192 "Could not mount $dev at $dir"
-    is_mountpoint $dir           || fatal 193 "Failed to mount $dev at $dir"
+    is_mountpoint $dir           && fatal 190 "Directory '%s' is already a mountpoint" "$dir"
+    PRETEND= cmd mkdir -p $dir   || fatal 191 "Failed to create directory '%s'" "$dir"
+    PRETEND= cmd mount $dev $dir || fatal 192 "Could not mount %s at %s" "$dev" "$dir"
+    is_mountpoint $dir           || fatal 193 "Failed to mount %s at %s" "$dev" "$dir"
 }
 
 do_partition() {
@@ -386,7 +386,7 @@ do_partition() {
     case $type in
           gpt) boot_flag=legacy_boot ;;
         msdos) boot_flag=boot        ;;
-            *) fatal 017 "Unknown partitioning scheme: $type.  Expected msdos or gpt"
+            *) fatal 017 "Unknown partitioning scheme: %s.  Expected msdos or gpt" "$type"
                ;;
     esac
 
@@ -411,7 +411,7 @@ do_makefs_ext() {
 do_makefs_fat() {
     local fat_dev=$1
     cmd mkfs.fat -n "LIVE-ESP" $fat_dev \
-        || fatal 211 "Could not make fat32 file system on $fat_dev"
+        || fatal 211 "Could not make fat32 file system on %s" "$fat_dev"
 }
 
 do_copy_ext() {
@@ -483,7 +483,7 @@ do_uuids() {
     local ext_dir=$1  ext_uuid=$2  grub_cfg=$3  fat_uuid=$4
     if [ ${#fat_uuid} -gt 0 ]; then
         local fat_file=$ext_dir/antiX/esp-uuid
-        cmd mkdir -p $(dirname $fat_file) || fatal 220 "Making directory $(dirname $fat_file) failed"
+        cmd mkdir -p $(dirname $fat_file) || fatal 220 "Making directory %s failed" "$(dirname $fat_file)"
         cmd write_file $fat_file $fat_uuid
     else
         warn "No UUID given for fat partition"
@@ -503,11 +503,11 @@ do_uuids() {
     if grep -q "search.*--set=root.*" $grub_cfg; then
         # Replace the line(s) if it/they exists
         cmd sed -i "/search.*--set=root.*/  s/.*/$new_line/" $grub_cfg \
-            || fatal 221 "sed on $(basename $grub_cfg) failed"
+            || fatal 221 "sed on %s failed" "$(basename $grub_cfg)"
     else
         # Add the new line before the first menuentry line if not
         cmd sed -ri "1,/^\s*menuentry/s/(^\s*menuentry)/$new_line\n\n\1/" $grub_cfg \
-            || fatal 222 "sed on $(basename $grub_cfg) failed"
+            || fatal 222 "sed on %s failed" "$(basename $grub_cfg)"
     fi
 }
 
@@ -518,7 +518,7 @@ do_install() {
     case $type in
           gpt) fname=gptmbr.bin ;;
         msdos) fname=mbr.bin    ;;
-            *) fatal 017 "Unknown partitioning scheme: $type.  Expected msdos or gpt"
+            *) fatal 017 "Unknown partitioning scheme: %s.  Expected msdos or gpt" "$type"
                ;;
     esac
 
@@ -529,8 +529,8 @@ do_install() {
         break
     done
 
-    [ "$file" ] || fatal 230 "Could not find file $fname"
-    cmd dd bs=440 conv=notrunc count=1 if=$file of=$usb_dev > /dev/null || fatal "dd command failed"
+    [ "$file" ] || fatal 230 "Could not find file %s" "$fname"
+    cmd dd bs=440 conv=notrunc count=1 if=$file of=$usb_dev > /dev/null || fatal 231 "dd command failed"
 
     local sdir idir syslinux_dir isolinux_dir
     for sdir in boot/syslinux syslinux; do
@@ -544,7 +544,7 @@ do_install() {
 
             warn "Create syslinux directory from %s" $idir
                 syslinux_dir=$ext_dir/${idir%isolinux}syslinux
-                cmd cp -r $ext_dir/$idir $syslinux_dir || fatal 231 "Could not copy the isolinux directory"
+                cmd cp -r $ext_dir/$idir $syslinux_dir || fatal 232 "Could not copy the isolinux directory"
                 local f
                 for f in $(cd $syslinux_dir && ls isolinux.*); do
                     test -e $ext_dir/$sdir/$f || continue
@@ -553,8 +553,8 @@ do_install() {
             break
         done
     fi
-    [ "$syslinux_dir" ] || fatal 232 "Could not find a syslinux or isolinux directory"
-    cmd extlinux -i $syslinux_dir || fatal 233 "extlinux command failed"
+    [ "$syslinux_dir" ] || fatal 233 "Could not find a syslinux or isolinux directory"
+    cmd extlinux -i $syslinux_dir || fatal 234 "extlinux command failed"
 }
 
 need() {
@@ -632,7 +632,8 @@ umount_all() {
     done
 
     mounted=$(mount | egrep "^$dev[^ ]*" | cut -d" " -f3 | grep .) || return 0
-    fatal 202 "One or more partitions on device $dev are in use at:\n  $(echo $mounted)"
+    local newline=$(printf "\n  ")
+    fatal 202 "One or more partitions on device %s are in use at:%s"  "$dev" "$newline$(echo $mounted)"
     return 1
 }
 
@@ -681,10 +682,10 @@ read_params() {
 
         # Deal with all options that take a parameter
         if takes_param "$arg"; then
-            [ $# -lt 1 ] && fatal "Expected a parameter after: -$arg"
+            [ $# -lt 1 ] && fatal "Expected a parameter after: %s" "-$arg"
             val=$1
             [ -n "$val" -a -z "${val##-*}" ] \
-                && fatal "Suspicious argument after -$arg: $val"
+                && fatal "Suspicious argument after %s: %s" "-$arg" "$val"
             SHIFT=$((SHIFT + 1))
             shift
         else
@@ -709,13 +710,13 @@ cmd() {
 
 check_size() {
     local type=$1  extra=$2  margin=$3
-    [ $extra -lt 0 ] && fatal "Not enough space on $type partition"
-    [ $extra -lt $margin ] && fatal "Less than $margin MiB would remain on $type partition"
+    [ $extra -lt 0 ] && fatal "Not enough space on %s partition" "$type"
+    [ $extra -lt $margin ] && fatal "Less than %s MiB would remain on %s partition" "$margin" "$type"
 }
 
 my_mkdir() {
     dir=$1
-    mkdir -p "$dir" || fatal "Could not make directory \"$dir\""
+    mkdir -p "$dir" || fatal "Could not make directory '%s'" "$dir"
 }
 
 du_size() {
