Must assign WORK_DIR before trap

diff --git a/live-usb-maker b/live-usb-maker
--- a/live-usb-maker
+++ b/live-usb-maker
@@ -168,6 +168,11 @@ main() {
         echo "$ALL_CMDS" | egrep -q "(^| )$cmd( |$)" || fatal "Unknown command: $cmd"
     done
 
+    WORK_DIR=$(mktemp -d /tmp/$ME-XXXX) \
+        || fatal "Could not make temporary work directory under /tmp"
+
+    chmod 755 $WORK_DIR
+
     trap clean_up EXIT
     start_log "$orig_args" "$CMDS" "$ISO_FILE" "$usb_dev"
 
@@ -185,10 +190,6 @@ main() {
     [ "$FORCE" ] || is_usb_or_removeable $usb_dev \
         || fatal "$usb_dev does not seem to be usb or removeable.  Use --force"
 
-    WORK_DIR=$(mktemp -d /tmp/$ME-XXXX) \
-        || fatal "Could not make temporary work directory under /tmp"
-
-    chmod 755 $WORK_DIR
 
     ISO_DIR=$WORK_DIR/iso
     EXT_DIR=$WORK_DIR/ext
