Only give error numbers for errors before we start logging

diff --git a/live-usb-maker b/live-usb-maker
--- a/live-usb-maker
+++ b/live-usb-maker
@@ -145,11 +145,11 @@ main() {
 
     local orig_args="$*"
 
-    test -r "$CONF_FILE" && . "$CONF_FILE"
+    #test -r "$CONF_FILE" && . "$CONF_FILE"
 
     [ $# -eq 0 ] && usage
 
-    EXIT_NUM=33  # Reading cmdline parameters
+    EXIT_NUM=10  # Reading cmdline parameters
     # This loop allows complete intermingling of filenames and options
     local opt_cnt=0
     while [ $# -gt 0 ]; do
@@ -167,17 +167,17 @@ main() {
         done
     done
 
-    [ $opt_cnt -lt 2 ] && fatal 011 "Expected at least two command line arguments"
+    [ $opt_cnt -lt 2 ] && fatal 020 "Expected at least two command line arguments"
 
     [ "$PRETEND" ] && msg "PRETEND MODE ENABLED"
 
     case $SIZE in
         [1-9]|[0-9][0-9]|100) ;;
-        *) fatal 012 "Bad size format '%s'.  Should be between 1 and 100 inclusive." "$(pqh $SIZE)"
+        *) fatal 021 "Bad size format '%s'.  Should be between 1 and 100 inclusive." "$(pqh $SIZE)"
     esac
 
-    [ -z "${FAT_SIZE##[0-9]}" ] && fatal 013 "esp-size must be larger than 9"
-    echo $FAT_SIZE | egrep -q "^[1-9][0-9]+$" || fatal 014 "esp-size must be an integer larger than 9"
+    [ -z "${FAT_SIZE##[0-9]}" ] && fatal 022 "esp-size must be larger than 9"
+    echo $FAT_SIZE | egrep -q "^[1-9][0-9]+$" || fatal 023 "esp-size must be an integer larger than 9"
 
     #echo "$CMDS" | egrep -q "(^| )pre( |$)"  && CMDS="$CMDS $PRE_CMDS"
     #echo "$CMDS" | egrep -q "(^| )post( |$)" && CMDS="$CMDS $POST_CMDS"
@@ -190,7 +190,7 @@ main() {
         cmd=${cmd%+}
         CMDS="$CMDS $(echo "$ORDERED_CMDS" | sed -rn "s/.*($cmd )/\1/p")"
         plus_cnt=$((plus_cnt + 1))
-        [ $plus_cnt -gt 1 ] && fatal 019 "Only one + command allowed"
+        [ $plus_cnt -gt 1 ] && fatal 024 "Only one + command allowed"
     done
 
     local force
@@ -199,16 +199,16 @@ main() {
     done
 
     EXIT_NUM=100
-    [ $UID -eq 0 ] || fatal 101 "This script must be run as root"
+    [ $UID -eq 0 ] || fatal "This script must be run as root"
 
     trap clean_up EXIT
     if which flock &> /dev/null; then
         exec 18> $LOCK_FILE
-        flock -n 18 || fatal 102 "A %s process is running.  If you think this is an error, remove %s" "$ME" "$LOCK_FILE"
+        flock -n 18 || fatal "A %s process is running.  If you think this is an error, remove %s" "$ME" "$LOCK_FILE"
         echo $$ >&18
     else
-        # fatal 103 "The %s program was not found."
-        EXIT_NUM=103 yes_NO_fatal "flock" \
+        # fatal "The %s program was not found."
+        yes_NO_fatal "flock" \
             "Do you want to continue without locking?" \
             "Use --force=flock to disable locking." \
             "The %s program was not found." "flock"
@@ -217,24 +217,23 @@ main() {
     # Write config file if one does not already exist
     test -e "$CONF_FILE" || write_conf "$CONF_FILE"
 
-    local usb_dev=$(expand_device $DEVICE) || fatal 110 "Could not find device %s" "$DEVICE"
+    local usb_dev=$(expand_device $DEVICE) || fatal "Could not find device %s" "$DEVICE"
 
-    mkdir -p $WORK_DIR || fatal 120 "Could not make a work directory under /tmp"
+    mkdir -p $WORK_DIR || fatal "Could not make a work directory under /tmp"
     chmod 755 $WORK_DIR
 
     start_log "$orig_args" "$CMDS" "$ISO_FILE" "$usb_dev"
 
     local dev_type=$(lsblk -no type --nodeps $usb_dev)
-    [ "$dev_type" = "disk" ] || fatal 130 "Device %s is not a disk device" $usb_dev
+    [ "$dev_type" = "disk" ] || fatal "Device %s is not a disk device" $usb_dev
 
-    test -e $usb_dev || fatal 140 "Device %s does not exist" $usb_dev
-    test -b $usb_dev || fatal 150 "Device %s is not a block device" $usb_dev
+    test -e $usb_dev || fatal "Device %s does not exist" $usb_dev
+    test -b $usb_dev || fatal "Device %s is not a block device" $usb_dev
 
     local ext_dev=$(get_partition $usb_dev 1)
     local fat_dev=$(get_partition $usb_dev 2)
 
-    # fatal 151 "The device %s does not seem to be usb or removeable."
-    EXIT_NUM=151
+    # fatal "The device %s does not seem to be usb or removeable."
     force usb || is_usb_or_removeable $usb_dev || yes_NO_fatal "usb" \
         "Do you want to use it anyway (dangerous!)" \
         "Use --force=usb to continue" \
@@ -246,9 +245,9 @@ main() {
     FAT_DIR=$WORK_DIR/fat
     MNT_DIR=$WORK_DIR/live-dev
 
-    mkdir $ISO_DIR $EXT_DIR $FAT_DIR || fatal 160 "Could not make %s subdirectories" "$WORK_DIR"
+    mkdir $ISO_DIR $EXT_DIR $FAT_DIR || fatal "Could not make %s subdirectories" "$WORK_DIR"
 
-    mount_iso "$ISO_FILE" $ISO_DIR || fatal 170 "Could not mount iso file %s" "$ISO_FILE"
+    mount_iso "$ISO_FILE" $ISO_DIR || fatal "Could not mount iso file %s" "$ISO_FILE"
 
     local iso_version version_file=$ISO_DIR/version
     if test -r $version_file && iso_version=$(cat $version_file 2>/dev/null) \
@@ -317,7 +316,7 @@ mount_iso() {
     local file=$1  dir=$2
     mkdir -p $dir
 
-    is_mountpoint $dir && fatal 171 "Directory '%s' is already a mountpoint" $dir
+    is_mountpoint $dir && fatal "Directory '%s' is already a mountpoint" $dir
 
     case $file in
         clone) mount_live $dir              ; return ;;
@@ -331,8 +330,8 @@ mount_iso() {
         mount -o ro "$file" $dir
         is_mountpoint $dir && return 0
     else
-        test -e "$file" || fatal 172 "Could not find iso file %s" "$file"
-        test -r "$file" || fatal 173 "Could not read iso file %s" "$file"
+        test -e "$file" || fatal "Could not find iso file %s" "$file"
+        test -r "$file" || fatal "Could not read iso file %s" "$file"
 
         local type
         for type in iso9660 udf; do
@@ -341,25 +340,25 @@ mount_iso() {
         done
     fi
 
-    fatal 175 "Could not mount iso file %s" "$file"
+    fatal "Could not mount iso file %s" "$file"
 }
 
 mount_live() {
     local targ_dir=$1  live_dir=${2:-$LIVE_MP}
 
-    is_mountpoint "$targ_dir" && fatal 181 "Live directory '%s' is already a mountpoint" "$targ_dir"
+    is_mountpoint "$targ_dir" && fatal "Live directory '%s' is already a mountpoint" "$targ_dir"
 
     # Allow live "directory" to be a device that we mount
     local block_dev=$(expand_device $live_dir)
     if [ ${#block_dev} -gt 0 ];  then
         my_mkdir $MNT_DIR
         mount -o ro $block_dev $MNT_DIR
-        is_mountpoint $MNT_DIR || fatal 182 "Could not mount device %s" "$block_dev"
+        is_mountpoint $MNT_DIR || fatal "Could not mount device %s" "$block_dev"
         live_dir=$MNT_DIR
     fi
 
-    test -d "$live_dir"       || fatal 183 "Live directory '%s' is not a directory"   "$live_dir"
-    is_mountpoint "$live_dir" || fatal 184 "Live directory '%s' is not a mountpoint"  "$live_dir"
+    test -d "$live_dir"       || fatal "Live directory '%s' is not a directory"   "$live_dir"
+    is_mountpoint "$live_dir" || fatal "Live directory '%s' is not a mountpoint"  "$live_dir"
 
     mount --bind $targ_dir $targ_dir
 
@@ -371,7 +370,7 @@ mount_live() {
         from="$live_dir/$dir"
         dest="$targ_dir/$dir"
         test -d "$from" || continue
-        mkdir -p "$dest" || fatal 186 "Could not create directory %s" "$dest"
+        mkdir -p "$dest" || fatal "Could not create directory %s" "$dest"
         mount --bind "$from" "$dest"
     done <<Live_Dirs
 $(cd "$live_dir" && eval "ls -d $LIVE_DIRS" 2>/dev/null)
@@ -382,8 +381,8 @@ Live_Dirs
         from="$live_dir/$file"
         dest="$targ_dir/$file"
         test -f "$from" || continue
-        mkdir -p "$(dirname "$dest")" || fatal 187 "Could not mkdir %s" "$(dirname "$dest")"
-        touch "$dest"                 || fatal 188 "Could not touch file %s" "$dest"
+        mkdir -p "$(dirname "$dest")" || fatal "Could not mkdir %s" "$(dirname "$dest")"
+        touch "$dest"                 || fatal "Could not touch file %s" "$dest"
         mount --bind "$from" "$dest"
     done <<Live_Files
 $(cd "$live_dir" && eval "ls -d $LIVE_FILES" 2>/dev/null)
@@ -392,10 +391,10 @@ Live_Files
 
 my_mount() {
     local dev=$1  dir=$2
-    is_mountpoint $dir           && fatal 190 "Directory '%s' is already a mountpoint" "$dir"
-    PRETEND= cmd mkdir -p $dir   || fatal 191 "Failed to create directory '%s'" "$dir"
-    PRETEND= cmd mount $dev $dir || fatal 192 "Could not mount %s at %s" "$dev" "$dir"
-    is_mountpoint $dir           || fatal 193 "Failed to mount %s at %s" "$dev" "$dir"
+    is_mountpoint $dir           && fatal "Directory '%s' is already a mountpoint" "$dir"
+    PRETEND= cmd mkdir -p $dir   || fatal "Failed to create directory '%s'" "$dir"
+    PRETEND= cmd mount $dev $dir || fatal "Could not mount %s at %s" "$dev" "$dir"
+    is_mountpoint $dir           || fatal "Failed to mount %s at %s" "$dev" "$dir"
 }
 
 do_partition() {
@@ -417,20 +416,20 @@ do_partition() {
         mkpart primary ext4  1         $ext_size   \
         mkpart primary fat32 $ext_size $mib_size   \
         set 1 $boot_flag on                        \
-        set 2 esp  on || fatal 205 "Partitioning failed"
+        set 2 esp  on || fatal "Partitioning failed"
 }
 
 do_makefs_ext() {
     local ext_dev=$1 local force_ext
     force makefs && force_ext="-F"
     cmd mkfs.ext4 $force_ext $EXT_OPTIONS -L "$EXT_LABEL" $ext_dev \
-        || fatal 210 "makefs" "Could not make ext4 file system on $ext_dev.  Perhaps try --force=makefs"
+        || fatal "makefs" "Could not make ext4 file system on $ext_dev.  Perhaps try --force=makefs"
 }
 
 do_makefs_fat() {
     local fat_dev=$1
     cmd mkfs.fat -n "LIVE-ESP" $fat_dev \
-        || fatal 211 "Could not make fat32 file system on %s" "$fat_dev"
+        || fatal "Could not make fat32 file system on %s" "$fat_dev"
 }
 
 do_copy_ext() {
@@ -444,7 +443,7 @@ do_copy_ext() {
         return
     fi
     msg "Copying files ..."
-    cmd cp -a $iso_dir/* $ext_dir/ || fatal 212 "Error when copying files to live usb"
+    cmd cp -a $iso_dir/* $ext_dir/ || fatal "Error when copying files to live usb"
     sync
 }
 
@@ -502,7 +501,7 @@ do_uuids() {
     local ext_dir=$1  ext_uuid=$2  grub_cfg=$3  fat_uuid=$4
     if [ ${#fat_uuid} -gt 0 ]; then
         local fat_file=$ext_dir/antiX/esp-uuid
-        cmd mkdir -p $(dirname $fat_file) || fatal 220 "Making directory %s failed" "$(dirname $fat_file)"
+        cmd mkdir -p $(dirname $fat_file) || fatal "Making directory %s failed" "$(dirname $fat_file)"
         cmd write_file $fat_file $fat_uuid
     else
         warn "No UUID given for fat partition"
@@ -522,11 +521,11 @@ do_uuids() {
     if grep -q "search.*--set=root.*" $grub_cfg; then
         # Replace the line(s) if it/they exists
         cmd sed -i "/search.*--set=root.*/  s/.*/$new_line/" $grub_cfg \
-            || fatal 221 "sed on %s failed" "$(basename $grub_cfg)"
+            || fatal "sed on %s failed" "$(basename $grub_cfg)"
     else
         # Add the new line before the first menuentry line if not
         cmd sed -ri "1,/^\s*menuentry/s/(^\s*menuentry)/$new_line\n\n\1/" $grub_cfg \
-            || fatal 222 "sed on %s failed" "$(basename $grub_cfg)"
+            || fatal "sed on %s failed" "$(basename $grub_cfg)"
     fi
 }
 
@@ -548,8 +547,8 @@ do_install() {
         break
     done
 
-    [ "$file" ] || fatal 230 "Could not find file %s" "$fname"
-    cmd dd bs=440 conv=notrunc count=1 if=$file of=$usb_dev > /dev/null || fatal 231 "dd command failed"
+    [ "$file" ] || fatal "Could not find file %s" "$fname"
+    cmd dd bs=440 conv=notrunc count=1 if=$file of=$usb_dev > /dev/null || fatal "dd command failed"
 
     local sdir idir syslinux_dir isolinux_dir
     for sdir in boot/syslinux syslinux; do
@@ -563,7 +562,7 @@ do_install() {
 
             warn "Create syslinux directory from %s" $idir
                 syslinux_dir=$ext_dir/${idir%isolinux}syslinux
-                cmd cp -r $ext_dir/$idir $syslinux_dir || fatal 232 "Could not copy the isolinux directory"
+                cmd cp -r $ext_dir/$idir $syslinux_dir || fatal "Could not copy the isolinux directory"
                 local f
                 for f in $(cd $syslinux_dir && ls isolinux.*); do
                     test -e $ext_dir/$sdir/$f || continue
@@ -572,8 +571,8 @@ do_install() {
             break
         done
     fi
-    [ "$syslinux_dir" ] || fatal 233 "Could not find a syslinux or isolinux directory"
-    cmd extlinux -i $syslinux_dir || fatal 234 "extlinux command failed"
+    [ "$syslinux_dir" ] || fatal "Could not find a syslinux or isolinux directory"
+    cmd extlinux -i $syslinux_dir || fatal "extlinux command failed"
 }
 
 need() {
@@ -630,8 +629,8 @@ umount_all() {
 
     mounted=$(mount | egrep "^$dev[^ ]*" | cut -d" " -f3 | grep .) || return 0
 
-    # fatal 201 "One or more partitions on device %s are mounted at: %s"
-    force umount || EXIT_NUM=201 yes_NO_fatal "umount" \
+    # fatal "One or more partitions on device %s are mounted at: %s"
+    force umount || yes_NO_fatal "umount" \
         "Do you want those partitions unmounted" \
         "Use --force=umount to have us try to unmount them" \
         "One or more partitions on device %s are mounted at:\n  %s" "$dev" "$(echo $mounted)"
@@ -652,7 +651,7 @@ umount_all() {
     done
 
     mounted=$(mount | egrep "^$dev[^ ]*" | cut -d" " -f3 | grep .) || return 0
-    fatal 202 "One or more partitions on device %s are in use at:\n  %s"  "$dev" "$(echo $mounted)"
+    fatal "One or more partitions on device %s are in use at:\n  %s"  "$dev" "$(echo $mounted)"
     return 1
 }
 
@@ -669,7 +668,7 @@ get_partition() {
 # Send "$@".  Expects
 #
 #   SHORT_STACK               variable, list of single chars that stack
-#   fatal(msg)                routine,  fatal("error message")
+#   fatal(msg)                routine,  fatal([errnum] "error message")
 #   takes_param(arg)          routine,  true if arg takes a value
 #   eval_argument(arg, [val]) routine,  do whatever you want with $arg and $val
 #
@@ -701,10 +700,10 @@ read_params() {
 
         # Deal with all options that take a parameter
         if takes_param "$arg"; then
-            [ $# -lt 1 ] && fatal "Expected a parameter after: %s" "-$arg"
+            [ $# -lt 1 ] && fatal 011 "Expected a parameter after: %s" "-$arg"
             val=$1
             [ -n "$val" -a -z "${val##-*}" ] \
-                && fatal "Suspicious argument after %s: %s" "-$arg" "$val"
+                && fatal 012 "Suspicious argument after %s: %s" "-$arg" "$val"
             SHIFT=$((SHIFT + 1))
             shift
         else
@@ -781,7 +780,6 @@ yes_NO_fatal() {
     [ ${#continuation} -gt 0 ] && fmt="$fmt  \n$continuation"
     fatal "$code" "$fmt" "$@"
 }
-
 
 YES_no() {  _yes_no 0 "yes" "$@" ;}
 yes_NO() {  _yes_no 1 "no"  "$@" ;}
@@ -901,7 +899,7 @@ fatal() {
     printf "${err_co}Fatal error:$hi_co $fmt$nc_co\n" "$@" >> $LOG_FILE
 
     printf "$code:$(echo "$fmt" | sed 's/\\n//g')\n" "$@" >> $ERR_FILE
-    my_exit ${EXIT_NUM:-333}
+    my_exit ${EXIT_NUM:-200}
 }
 
 my_exit() {
